### ISSUE TITLE
use aem-boilerplate-commerce as source

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#1]
start using the commerce boiler plate code -  https://github.com/hlxsites/aem-boilerplate-commerce

**Comment by amol-anand** [comment]
Not needed since customer is not setup to use it. They are currently using GQL approach instead.

**Comment by kmurugulla** [comment]
Since we decided to use the sites boilerplate and no need for using commerce one as there is no scope to use the drop ins as such in building commerce landing pages, will be closing this ticket
