### ISSUE TITLE
Reusable banner fragment

### ISSUE THREAD

**Issue by amol-anand** [aemsites/sling#10]
Can be authored with Column block.
Needs to allow 2 images, Desktop size and Mobile size.
Should be a fragment that can be reused across multiple pages.

![Screenshot 2024-05-21 at 2 48 55 PM](https://github.com/aemsites/sling/assets/7074782/3eb9f97c-d12c-4194-9a51-73726895222f)

The image could be different from what is live on site https://www.sling.com/

**Comment by helms-charity** [comment]
Note: currently on our home page, the background image is added only on "blog-hero" block, so it doesn't cover the "columns" block content where the CTA banner text and button is. 

![image](https://github.com/user-attachments/assets/bc4d8439-48c7-49b9-b5c5-b4e505f3219d)

**Comment by helms-charity** [comment]
this was done.
