### ISSUE TITLE
[import] modify script to add gamefinder, table variants

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#118]
- [x] modify import script to add gamefinder 
(see https://main--sling--aemsites.aem.page/whatson/sports/college-basketball/watch-womens-final-four-live, https://main--sling--aemsites.aem.page/whatson/sports/nfl/watch-nfl-network-live,
https://main--sling--aemsites.aem.page/whatson/sports/college-basketball/watch-womens-sweet-16-live)
- [x] table block color variants
 (see multiple "NBA sling tv weekly preview" pages such as https://main--sling--aemsites.aem.page/whatson/sports/nba/nba-sling-tv-weekly-preview-may-10)

-- more added by Charity --

- [x]  Need to add "strong" to any heading with inlined CSS for text-align: center

![image](https://github.com/aemsites/sling/assets/3883795/bb7986c5-f5c8-4a82-817e-da60240df675)

- [x] Need to look at pages with embedded X posts and Facebook Watch in them, such as on this page

 https://main--sling--aemsites.aem.page/whatson/sports/combat-sports/stream-bkfc-48-live

**Comment by kmurugulla** [comment]
@helms-charity @amol-anand - i am not creating a PR since we are keeping the "import" code in "import" branch. But please get the latest if you are trying to run the import script

**Comment by helms-charity** [comment]
I have labeled all the tickets that probably need inclusion in the import script with a new label.
