### ISSUE TITLE
Fix: ad-hoc anchor links

### ISSUE THREAD

**Issue by helms-charity** [aemsites/sling#122]
**Background**
I found 1 (so far) "jump to a section" on https://www.sling.com/whatson/entertainment/exclusives/black-history-month-sling-tv . These are anchor links to areas lower on the page. 
- These are currently authored as H2, but with a font size override.
- The IDs of the H2s that they link to lower on the page have custom IDs (not the same as what Helix adds).

Our version: https://main--sling--aemsites.aem.page/whatson/entertainment/exclusives/black-history-month-sling-tv
The import script is importing the hashtag + anchor name on the link correctly, but the links are being imported as hard coded live site links (to sling.com, not relative to the domain). I re-authored these as H4 links.

The Sling team doesn't think this is used very often but they do want the option.

**Solution**
We can manually author them to be H4s and update the hashtag + ID to match the Helix version.
Does the import script need to be modified to not hard code the domain?

**Comment by kmurugulla** [comment]
@helms-charity - made the changes to the import script - https://github.com/aemsites/sling/commit/e0714bf1c09ab25c16f942ccf77b5a7055fd4163
