### ISSUE TITLE
Blog CTA fragments, section variants needed

### ISSUE THREAD

**Issue by helms-charity** [aemsites/sling#127]
Per Mark Schiff, the blog CTA buttons are fragments and there is no formula for which ones are authored on which page.

There are about 12 CTA fragments that exist, but 90% of blog articles use the 4 below.
Here are example pages with the exfrags:

Blue Efrag - https://www.sling.com/whatson/sports/golf/us-open-golf
Orange Efrag - https://www.sling.com/whatson/sports/nba/NBA-Playoff-schedule-how-to-watch-sling-tv
Combo Efrag - https://www.sling.com/whatson/sports/nfl/stream-nfl-draft-live
Combo w/ Sports Extras - https://www.sling.com/whatson/sports/nba/wnba-schedule-sling-tv
Sling Blue w/ Sports - https://www.sling.com/whatson/sports/nhl/nhl-stanley-cup-playoffs-schedule-sling - has different style?

Here are the actual exfrags:

Blue Efrag - /content/experience-fragments/sling/homepage_redesign/blog/cta1

Orange Efrag - /content/experience-fragments/sling/homepage_redesign/blog/cta

Combo Efrag - /content/experience-fragments/sling/homepage_redesign/blog/cta11

Combo with Sports Cart Link - /cart/magento/account?classification=us&plan=one-month&plan_offer=extra-stair-step-2&sb=sling-combo&ats=sports-extra

Note that these are rendered as a button in Desktop size that converts into a sticky footer banner in Mobile size. 
The import script needs to be adjusted so that it gets the correct CTA fragment.

2. "TRY SLING TV TODAY!" seen on https://www.sling.com/whatson/entertainment/exclusives/black-history-month-sling-tv . It looks like the import script is assigning the fragment link from # 1, so this will need to be changed once another Fragment is authored.

3. "SLING BLUE W SPORTS" as seen https://www.sling.com/whatson/sports/nhl/nhl-stanley-cup-playoffs-schedule-sling . 
I can see that the link is being imported, but it doesn't have class of "button primary" because the > is being converted to the text "caret". A new fragment needs to be authored, and then the import script updated/corrected.
![image](https://github.com/aemsites/sling/assets/3883795/c174fcc0-e805-418d-87de-42917fa3a801)

(Also note this one has a different mobile banner style than # 2)
![image](https://github.com/aemsites/sling/assets/3883795/6d79c356-85b9-402a-b918-6a97e13ef9c4)

4. Arabic version https://www.sling.com/whatson/international/arabic/lebanese-2024-series-ar
Unlike the sports pages, the button link on Arabic pages was not imported, only the button text.
![image](https://github.com/aemsites/sling/assets/3883795/0295cb5a-9170-43b7-8278-091aea13c698)

**Comment by kmurugulla** [comment]
Handling different CTA types in import script
