### ISSUE TITLE
Section Meta based CSS for Arabic language pages

### ISSUE THREAD

**Issue by helms-charity** [aemsites/sling#130]
For pages that are written in the Arabic language, the text alignment needs to go from right to left.
 See example:
https://www.sling.com/whatson/international/arabic/lebanese-2024-series-ar

Let's go with a section metadata, to add a class of "rtl" which seems like it would satisfy the use case as long as no new sections are added.

**Comment by helms-charity** [comment]
Here is the CSS for section metadata.
`.section.rtl, .section.rtl h2, .section.rtl h3,
.section.rtl h4, .section.rtl h5, .section.rtl h6,
.section.rtl p, .section.rtl ul, .section.rtl ol {
  text-align: right;
}`

**Comment by kmurugulla** [comment]
@rusmeenkhan1 @helms-charity - closing this issue as it has been worked on today
