### ISSUE TITLE
Whats on - Article page

### ISSUE THREAD

**Issue by amol-anand** [aemsites/sling#14]
https://www.sling.com/whatson/sports/golf/watch-pga-championship-live
https://www.sling.com/whatson/sports/golf/watch-ryder-cup-live

- [ ] Hero image
- [ ] Breadcrumb (auto-gen)
- [ ] Author info (auto-blocked) - Image, name, Publish date, Tags, Social
- [ ] Article (can include content like images, youtube videos get auto-embedded, add any blocks here like table)
- [ ] CTA Fragment (TRY SLING TV TODAY with offer details)
- [ ] Most Popular articles in that section
- [ ] Email / Subscribe Fragment

**Comment by kmurugulla** [comment]
Reopening as all the tasks in this are are not complete
