### ISSUE TITLE
content: Offer details modals authoring

### ISSUE THREAD

**Issue by helms-charity** [aemsites/sling#159]
On the homepage are cards with "offer details" links under them, as well as text under buttons, that open up large text documents in a modal.
In AEM, these are authored by selecting an Experience Fragment as a link that is pre-programmed to open in a modal.

![image](https://github.com/user-attachments/assets/3f9a40e8-78d6-4631-b425-edd7fd5c5ca1)

![image](https://github.com/user-attachments/assets/8700da4c-9e3d-4b2c-8616-1261e7ee5788)

NOTE: These are working fine in Blog pages, such as here:
https://main--sling--aemsites.aem.live/whatson/sports/college-football/rece-davis-college-gameday-interview

**Comment by neetunegi** [comment]
I updated the correct path for the fragment , now the modal is opening . please review and let me know in case you see issues. @helms-charity

**Comment by helms-charity** [comment]
THank you, I will close.
