### ISSUE TITLE
Update blog-hero gradients + image

### ISSUE THREAD

**Issue by helms-charity** [aemsites/sling#180]
Sling has changed their gradients and the image in the top banner of the 1st level category pages. See https://www.sling.com/whatson/announcements for a new example.

Task: please update these gradients based on the live site the way they look in Mobile view, because I noticed you can't see the full gradient in wider screens. For example, we should capture the orange and black:
![image](https://github.com/user-attachments/assets/7a00d239-abaf-4a46-99bb-ba12d6ea462a)

Also, the image is only "whats on", so new desktop + mobile images need to be used. See https://main--sling--aemsites.aem.page/whatson/announcements for example where I have updated it already, copy + paste to the others.
blog-hero.css
![image](https://github.com/user-attachments/assets/f812be4d-c61c-4994-93c8-962b43d041e0)

**Comment by helms-charity** [comment]
After looking at the new colors, let's do this.

/whatson = "red", DONE
/whatson/announcements = "cyan", UPDATE EXISTING VALUES (in progress)
/whatson/sports = "green", ADD NEW CLASS/STYLE
/whatson/entertainment = "dark-orange", ADD NEW CLASS/STYLE
/whaston/movies = "blue", UPDATE EXISTING VALUES
/whatson/international = "yellow", ADD NEW CLASS/STYLE
/whatson/freestream = "orange", ADD NEW CLASS/STYLE

You can leave the other colors in the css file for now as other options.

**Comment by neetunegi** [comment]
for yellow i have to go with more color points to match sling otherwise it was not at all matching. it was looking very dull compared to sling.
