### ISSUE TITLE
Promotion Banner Fragment

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#209]
Create and Style the Fragment that can be used on home page 

Author should be able to edit 
- the image appears on the right columns
- the CTA appears on the banner

Sample

![image](https://github.com/user-attachments/assets/61e1c634-8a1b-412d-856a-1a810f642dd6)

More details - watch the [video](https://adobe.sharepoint.com/sites/DishPurchasingCorporation/Shared%20Documents/2%20-%20AEM/2024/Sling.com%20Edge%20Delivery%20Project/24.07.30%20Adobe_Dish%20-%20Sling.com%20Author%20Team%20Review.mp4?csf=1&amp;web=1&amp;e=PPajWV&CID=6e0ac57a-034e-4f7b-a242-98dd6c1b45e0)  from 27:15 to 30

**Comment by helms-charity** [comment]
@kmurugulla we already have a "Global banner" https://github.com/aemsites/sling/tree/main/aemedge/blocks/global-banner , do we have another name for this? Or are you thinking this is a variant of the same?

**Comment by kmurugulla** [comment]
@helms-charity Changing the Name to Promotion Banner to distinguish it from existing gloabl banner .

**Comment by gayatritulamandi-sling** [comment]
@kmurugulla I am unable to access Video

**Comment by helms-charity** [comment]
@gayatritulamandi-sling I have created a share link for that video.

https://adobe.sharepoint.com/:v:/s/DishPurchasingCorporation/EZGYALcKXJVFmDFIEJB1w4YB2QORtYyerAk5v5MH4z26WA?email=gayatri.tulamandi%40dish.com&e=HxZdC7&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Comment by gayatritulamandi-sling** [comment]
I am getting like this, tried all other sign in options, but no luck

![image](https://github.com/user-attachments/assets/fcd000ff-4b3c-4475-be2e-5104049652d8)

**Comment by helms-charity** [comment]
Oh I see it is uploaded to Google drive. See in this directory https://drive.google.com/drive/folders/1X2pnXOlby6vZWYM6ki6nGpt-WqoAi7B1

**Comment by gayatritulamandi-sling** [comment]
ok cool, Now I can, Thank you

**Comment by helms-charity** [comment]
This was done via another ticket, closing.
