### ISSUE TITLE
H1 - H6 text wrap correction

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#248]
Ref - https://www.b.sling.com/whatson/sports/baseball/mlb-all-star-game-4k

![image](https://github.com/user-attachments/assets/778ac4a0-bc9f-4804-ad23-aa4b0b03d0b4)

Expected 

![Screenshot 2024-08-13 at 3 27 01 PM](https://github.com/user-attachments/assets/f464ccdc-bdc1-4f49-aa7d-7f9b58ddc184)

**Comment by helms-charity** [comment]
This is horrible looking though. Why do they want orphaned words is beyond me, but OK.
