### ISSUE TITLE
importing twitter & facebook videos videos

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#251]
Ref - https://www.sling.com/whatson/sports/golf/us-open-golf

Make sure the twitter video embeds are working

Video url - https://x.com/KylePorterCBS/status/1799925674863431986?host=https%253A%252F%252Fwww.sling.com

**Comment by helms-charity** [comment]
Twitter's api doesn't accept "x.com" links. They MUST be twitter.com links. So, this is fixed and published.

**Comment by helms-charity** [comment]
If the embedded image of the tweet should be removed, please do that and close this ticket.

**Comment by kmurugulla** [comment]
@helms-charity - updating the ticket with one more item to look at 
FB videos - 
![image](https://github.com/user-attachments/assets/675e86d1-798d-4146-98e2-61346aea4b48)
