### ISSUE TITLE
Image Carousel for Blog Articles

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#257]
Sample Page - https://www.sling.com/whatson/entertainment/drama/stream-feud-capote-swans
EDS - https://main--sling--aemsites.hlx.live/whatson/entertainment/drama/stream-feud-capote-swans

Please wait to watch the carousel in action in this area on that page

![image](https://github.com/user-attachments/assets/f5a65379-b7a0-4f30-ba38-66dfee345319)

**Comment by helms-charity** [comment]
wow... I never would have noticed that.
