### ISSUE TITLE
jump links in the page not working

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#264]
reference - https://www.b.sling.com/whatson/entertainment/exclusives/black-history-month-sling-tv
clicking on any of the following is not taking the user to the corresponding section

![image](https://github.com/user-attachments/assets/1bbf7d19-8e38-4d63-8eb2-06c1758eae09)

**Comment by helms-charity** [comment]
Black history month fixed, now I will fix 
https://main--sling--aemsites.aem.live/whatson/sports/general-sports/live-sports-schedules-sling-tv

**Comment by helms-charity** [comment]
All set.
