### ISSUE TITLE
Performance issue for FB and other embeds/vids

### ISSUE THREAD

**Issue by helms-charity** [aemsites/sling#278]
## facebook video causing CLS?

This page has the only video that will play outside of www.sling.com, so testing is limited. You'll want to create a test page with a few of this same Facebook video.
https://main--sling--aemsites.aem.live/whatson/sports/college-football/rece-davis-college-gameday-interview

## Pagespeed says the desktop wants a facade for the Youtube vid:
- https://pagespeed.web.dev/analysis/https-main--sling--aemsites-aem-live-whatson-sports-college-football-rece-davis-college-gameday-interview/dly68xdr7d?form_factor=desktop

**Comment by kmurugulla** [comment]
Not an issue any more - https://pagespeed.web.dev/analysis/https-www-sling-com-whatson-sports-college-football-rece-davis-college-gameday-interview/5f2qg71gbo?form_factor=mobile
