### ISSUE TITLE
Content Import - Import Script 

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#40]
Consolidating the list issues that we may need to look into 

- [ ] the content of the full webpage is not imported (https://main--sling--aemsites.hlx.page/whatson/movies/tcm-women-make-film-preview)
- [ ] All the images are not importing correctly (https://main--sling--aemsites.hlx.page/whatson/announcements/new-product-features)

**Comment by amol-anand** [comment]
@kmurugulla for the first url - i see all images showing up. what am i missing? (it might not just be aligned center?)
second link I do see the extra caret button showing up. can update the import script to clean that up as well.

**Comment by amol-anand** [comment]
https://github.com/aemsites/sling/pull/53 just tried the first url and it looks fine to me.

**Comment by amol-anand** [comment]
Ok I see the issue with the first URL - the original has a youtube url in the content as an A tag but not necessarily as an embed. fixing that

**Comment by amol-anand** [comment]
https://www.sling.com/whatson/announcements/new-product-features 
has an image carousel with 2 images swiping between each other. I can add the content to a carousel block.
