### ISSUE TITLE
Allow Empty Contents in Top Nav

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#422]
![image](https://github.com/user-attachments/assets/2ac1f32f-f4a5-4182-88cc-d2c5a8bd72d2)

On https://www.sling.com/programming/sports/pro-football the top nav does not have any links but in the current code , if there are no links / text , it will not render. 

Hence in the Top Nav on the page - https://main--sling--aemsites.hlx.live/programming/sports/pro-football added a link.

**Comment by RitwikSrivastava** [comment]
<img width="1660" alt="Screenshot 2024-12-02 at 3 08 40 PM" src="https://github.com/user-attachments/assets/af24ebbd-4570-4da8-b110-1551bc5c5c9a">
If we keep the bullet without any links/text, then it renders an empty top nav as below. 

<img width="1664" alt="Screenshot 2024-12-02 at 3 08 58 PM" src="https://github.com/user-attachments/assets/18ae0784-73a6-4de8-8d20-39f3f164ef37">

**Comment by RitwikSrivastava** [comment]
Its working the same as in original site - https://main--sling--aemsites.hlx.live/programming/sports/pro-football
