### ISSUE TITLE
Sports page layout issues

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#448]
Check for icons in "supported devices"
- icon sizes are not matching and 
- last row icons are cutting off 

Check font alignment everywhere, such as:
![image](https://github.com/user-attachments/assets/e6b7eb41-b4d0-4b57-a19e-e4a8535cf8ce)

**Comment by RitwikSrivastava** [comment]
This issue also cant be reproduced on responsive dimension on browser. But can be spotted on IOS device browser.

**Comment by kmurugulla** [comment]
@RitwikSrivastava @rusmeenkhan1 - try and see whether you can reproduce this issue on Safari . The icon size issue must be easy to fix . Please work on it

**Comment by RitwikSrivastava** [comment]
https://github.com/aemsites/sling/pull/472 this fixes the font alignment in mobile and tablet view.
