### ISSUE TITLE
Arabic Blogs has Related Items - Are they needed ?

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#45]
Would like to check whether the related section at the bottom is required for all blogs or only for arabic .

https://www.sling.com//whatson/international/arabic/lebanese-2024-series-ar

**Comment by amol-anand** [comment]
Question for customer. Haven't seen this block anywhere else. Seems like a good one to not bring over.

**Comment by kmurugulla** [comment]
As per the confirmation from Sling.com team we are not implementing this , so closing this ticket
