### ISSUE TITLE
Mobile Header - Styling Issues

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#454]
![Mobile-Header-IOS](https://github.com/user-attachments/assets/8cec43cb-d3e4-43d6-b07c-3600bd3ab727)

" on my mobile device that the alignment of text and images is off. i.e. the sling logo in the header, the marquee image, the text in the CTA buttons. I don’t see the same issue when I am on desktop. "

**Comment by RitwikSrivastava** [comment]
<img width="639" alt="Screenshot 2024-12-04 at 12 33 55 PM" src="https://github.com/user-attachments/assets/c81866ec-4fba-459a-b440-ba22e4005a59">
Developer Tools change device to mobile renders it fine. but yeah on actual phone browser this doesn't renders correctly.

**Comment by kmurugulla** [comment]
@RitwikSrivastava - (fyi) It's interesting that I can't reproduce this in the browser when testing with the "responsive" tab. But when i load it on the IOS device , i do see the issue mentioned above.

**Comment by RitwikSrivastava** [comment]
> @RitwikSrivastava - (fyi) It's interesting that I can't reproduce this in the browser when testing with the "responsive" tab. But when i load it on the IOS device , i do see the issue mentioned above.

Yes, i am also seeing the same behaviour. Not sure how to fix these types of issues ? if i cant see them on my desktop browser responsive tab.

**Comment by kmurugulla** [comment]
I found out that this issue is reproducible in Safari and fixing it
