### ISSUE TITLE
Fonts CLS on Whatson Category pages

### ISSUE THREAD

**Issue by amol-anand** [aemsites/sling#71]
https://pagespeed.web.dev/analysis/https-search--sling--aemsites-aem-live-whatson-sports-tennis/hhck777d7m?form_factor=mobile

**Comment by helms-charity** [comment]
The big card CLS shift was addressed in PR #78 . However, the H1 and other font sizes need to be changed more globally to get the rest, which this ticket's scope will cover.

**Comment by kmurugulla** [comment]
This seem like an issue that was resolved already 

no CLS on main branch - https://pagespeed.web.dev/analysis/https-main--sling--aemsites-aem-live-whatson-sports-tennis/s7q4mo5uw7?form_factor=mobile
