### ISSUE TITLE
whatson: table block variant 

### ISSUE THREAD

**Issue by kmurugulla** [aemsites/sling#95]
we may need a variant 

![image](https://github.com/aemsites/sling/assets/7944122/a94f98a9-e33d-4337-86ef-efeabe8aa1b8)

references 
- https://www.sling.com/whatson/sports/baseball/mlb-network-free-preview
- https://www.sling.com/whatson/sports/general-sports/stream-nascar-racing-live

**Comment by helms-charity** [comment]
@rusmeenkhan1 it seems besides "schedule" variant, there are different table headers. So the one above could be "schedule, blue" and this one here at https://www.sling.com/whatson/sports/nhl/nhl-stanley-cup-playoffs-schedule-sling could be "schedule, cyan" maybe?
